UNT_REGISTERED 2026-04-27T09:57:19.011Z DEBUG 1 --- [auth-service] [   scheduling-1] o.s.data.mongodb.core.MongoTemplate      : Saving Document containing fields: [_id, aggregateId, aggregateType, eventType, payload, status, retryCount, errorMessage, createdAt, lastModifiedAt, active, _class] 2026-04-27T09:57:19.049Z DEBUG 1 --- [auth-service] [   scheduling-1] o.s.data.mongodb.core.MongoTemplate      : Saving Document containing fields: [_id, aggregateId, aggregateType, eventType, payload, status, retryCount, errorMessage, createdAt, lastModifiedAt, active, _class] 2026-04-27T09:57:19.052Z ERROR 1 --- [auth-service] [   scheduling-1] c.b.c.publisher.OutboxEventPublisher     : ❌ Failed to publish event to Kafka: eventId=69ef2f0342f24603cd0d657e, retryCount=4
org.apache.kafka.common.KafkaException: java.lang.UnsatisfiedLinkError: /tmp/snappy-1.1.10-e57034a7-3a63-4f0a-9cba-062b8fcce1ac-libsnappyjava.so: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /tmp/snappy-1.1.10-e57034a7-3a63-4f0a-9cba-062b8fcce1ac-libsnappyjava.so)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[na:na]
        at java.base/java.util.concurrent.Executors.call(Executors.java:572) ~[na:na]
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358) ~[na:na]
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.run(ThreadPoolExecutor.java:642) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[na:na]
Caused by: java.lang.UnsatisfiedLinkError: /tmp/snappy-1.1.10-e57034a7-3a63-4f0a-9cba-062b8fcce1ac-libsnappyjava.so: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /tmp/snappy-1.1.10-e57034a7-3a63-4f0a-9cba-062b8fcce1ac-libsnappyjava.so)
        at java.base/jdk.internal.loader.NativeLibraries.load(Native Method) ~[na:na]
        at java.base/jdk.internal.loader.NativeLibraries.open(NativeLibraries.java:331) ~[na:na]
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:197) ~[na:na]
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:139) ~[na:na]
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2418) ~[na:na]
        at java.base/java.lang.Runtime.load0(Runtime.java:852) ~[na:na]
        at java.base/java.lang.System.load(System.java:2025) ~[na:na]